/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard
-/
module

public import FLT.Data.Hurwitz
public import FLT.Data.QHat
import Mathlib.CategoryTheory.Category.Init
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.Tactic.Positivity.Finset

/-!
# Adelic Hurwitz quaternions

Base changes of the Hurwitz integers to `ℚ` and to `ZHat`, providing a
quaternion algebra over the rationals and its profinite completion as
free rank-4 modules over the corresponding base ring.

## Main definitions

* `HurwitzRat`: the rational quaternions `ℚ + ℚi + ℚj + ℚk`.
* `HurwitzHat`: the profinite Hurwitz quaternions, a free rank-4 module
  over `ZHat`.
-/

@[expose] public section

open scoped TensorProduct

/-- The base change of the Hurwitz quaternions to ZHat. -/
noncomputable def HurwitzHat : Type := 𝓞 ⊗[ℤ] ZHat

namespace HurwitzHat

/-- The base change of the Hurwitz quaternions to ZHat. -/
scoped notation "𝓞^" => HurwitzHat

noncomputable instance : Ring 𝓞^ := Algebra.TensorProduct.instRing

end HurwitzHat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
noncomputable def HurwitzRat : Type := ℚ ⊗[ℤ] 𝓞

namespace HurwitzRat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
scoped notation "D" => HurwitzRat

noncomputable instance : Ring D := Algebra.TensorProduct.instRing

end HurwitzRat

open scoped HurwitzRat HurwitzHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
noncomputable def HurwitzRatHat : Type := D ⊗[ℤ] ZHat

namespace HurwitzRatHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
scoped notation "D^" => HurwitzRatHat

noncomputable instance : Ring D^ := Algebra.TensorProduct.instRing

private noncomputable instance : Module.IsTorsionFree ℤ (Quaternion ℝ) :=
  Module.IsTorsionFree.of_smul_eq_zero fun z q h => by
    by_cases hz : z = 0
    · exact Or.inl hz
    · right
      have hzR : (z : ℝ) ≠ 0 := by exact_mod_cast hz
      apply (smul_eq_zero_iff_right hzR).mp
      simpa [Int.cast_smul_eq_zsmul] using h

private noncomputable instance : Module.IsTorsionFree ℤ 𝓞 :=
  Hurwitz.toQuaternion_injective.moduleIsTorsionFree Hurwitz.toQuaternion
    (fun r m => Hurwitz.toQuaternion_zsmul m r)

private noncomputable instance : Module.Flat ℤ ℚ := inferInstance

private noncomputable instance : Module.Flat ℤ 𝓞 := inferInstance

private noncomputable instance : Module.Flat ℤ D := by
  change Module.Flat ℤ (ℚ ⊗[ℤ] 𝓞)
  infer_instance

private noncomputable instance : Module.Flat ℤ 𝓞^ := by
  change Module.Flat ℤ (𝓞 ⊗[ℤ] ZHat)
  infer_instance

/-- The inclusion from D=ℚ+ℚi+ℚj+ℚk to D ⊗ 𝔸, with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₁ : D →ₐ[ℤ] D^ := Algebra.TensorProduct.includeLeft
-- (Algebra.TensorProduct.assoc ℤ ℚ 𝓞 ZHat).symm.trans Algebra.TensorProduct.includeLeft

lemma injective_hRat :
    Function.Injective j₁ := by
  exact Algebra.TensorProduct.includeLeft_injective
    (R := ℤ) (S := ℤ) (A := D) (B := ZHat)
    (RingHom.injective_int (algebraMap ℤ ZHat))

-- this stopped working in 4.29
noncomputable instance : Ring (ℚ ⊗[ℤ] 𝓞^) := Algebra.TensorProduct.instRing

-- this stopped working in 4.29
noncomputable instance : Ring (D ⊗[ℤ] ZHat) := Algebra.TensorProduct.instRing

-- in 4.29 I had to change all three ⊗ in the below to ⊗[ℤ]
/-- The inclusion from the profinite Hurwitz quaternions to to 𝔸+𝔸i+𝔸j+𝔸k,
with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₂ : 𝓞^ →ₐ[ℤ] D^ :=
  ((Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat).symm : ℚ ⊗[ℤ] 𝓞^ ≃ₐ[ℤ] D ⊗[ℤ] ZHat).toAlgHom.comp
  (Algebra.TensorProduct.includeRight : 𝓞^ →ₐ[ℤ] ℚ ⊗[ℤ] 𝓞^)

lemma injective_zHat :
    Function.Injective j₂ := by
  unfold j₂
  intro x y hxy
  apply Algebra.TensorProduct.includeRight_injective
    (R := ℤ) (A := ℚ) (B := 𝓞^)
    (RingHom.injective_int (algebraMap ℤ ℚ))
  exact (Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat).symm.injective hxy

private lemma tensorRat_canonicalForm (z : ℚ ⊗[ℤ] 𝓞^) :
    ∃ (N : ℕ+) (z' : 𝓞^), z = (1 / N : ℚ) ⊗ₜ z' := by
  induction z using TensorProduct.induction_on with
  | zero =>
    refine ⟨1, 0, ?_⟩
    simp
  | tmul q z =>
    refine ⟨⟨q.den, q.den_pos⟩, q.num * z, ?_⟩
    simp_rw [← zsmul_eq_mul, TensorProduct.tmul_smul, TensorProduct.smul_tmul']
    simp only [PNat.mk_coe, zsmul_eq_mul]
    simp only [← q.mul_den_eq_num, mul_assoc, one_div, ne_eq, Nat.cast_eq_zero,
      Rat.den_ne_zero, not_false_eq_true, mul_one, mul_inv_cancel₀]
  | add x y hx hy =>
    obtain ⟨N₁, z₁, rfl⟩ := hx
    obtain ⟨N₂, z₂, rfl⟩ := hy
    refine ⟨N₁ * N₂, (N₁ : ℤ) * z₂ + (N₂ : ℤ) * z₁, ?_⟩
    simp only [TensorProduct.tmul_add, ← zsmul_eq_mul,
      TensorProduct.tmul_smul, TensorProduct.smul_tmul']
    simp only [one_div, PNat.mul_coe, Nat.cast_mul, mul_inv_rev, zsmul_eq_mul,
      Int.cast_natCast, ne_eq, Nat.cast_eq_zero, PNat.ne_zero, not_false_eq_true,
      mul_inv_cancel_left₀]
    rw [add_comm]
    congr
    simp [mul_comm]

-- should I rearrange tensors? Not sure if D^ should be (ℚ ⊗ 𝓞) ⊗ ℤhat or ℚ ⊗ (𝓞 ⊗ Zhat)
lemma canonicalForm (z : D^) :
    ∃ (N : ℕ+) (z' : 𝓞^), z = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z' := by
  let e : D^ ≃ₐ[ℤ] (ℚ ⊗[ℤ] 𝓞^) := by
    change ((ℚ ⊗[ℤ] 𝓞) ⊗[ℤ] ZHat) ≃ₐ[ℤ] (ℚ ⊗[ℤ] (𝓞 ⊗[ℤ] ZHat))
    exact Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat
  obtain ⟨N, z', hz⟩ := tensorRat_canonicalForm (e z)
  refine ⟨N, z', ?_⟩
  apply e.injective
  rw [hz, map_mul]
  have hj₁ : e (j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D)) =
      (N⁻¹ : ℚ) ⊗ₜ (1 : 𝓞^) := by
    change (Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat)
      ((((N⁻¹ : ℚ) ⊗ₜ[ℤ] (1 : 𝓞)) : D) ⊗ₜ[ℤ] (1 : ZHat)) = _
    rfl
  have hj₂ : e (j₂ z') = (1 : ℚ) ⊗ₜ z' := by
    change e (e.symm ((1 : ℚ) ⊗ₜ[ℤ] z')) = _
    simp
  rw [hj₁, hj₂]
  have hmul : (((N⁻¹ : ℚ) ⊗ₜ[ℤ] (1 : 𝓞^)) *
      ((1 : ℚ) ⊗ₜ[ℤ] z')) = (N⁻¹ : ℚ) ⊗ₜ[ℤ] z' := by
    calc
      _ = ((N⁻¹ : ℚ) * 1) ⊗ₜ[ℤ] ((1 : 𝓞^) * z') :=
        Algebra.TensorProduct.tmul_mul_tmul (R := ℤ)
          (N⁻¹ : ℚ) (1 : ℚ) (1 : 𝓞^) z'
      _ = _ := by rw [mul_one, one_mul]
  simpa [one_div] using hmul.symm

lemma completed_units (z : D^ˣ) : ∃ (u : Dˣ) (v : 𝓞^ˣ), (z : D^) = j₁ u * j₂ v := sorry

end HurwitzRatHat
